# $Id: makefile,v 1.2 2000/10/29 12:19:42 cwohlgemuth Exp $ 

#===================================================================================================
#
#	 This Makefile makes the Generic Plugin DLL (plugin.dll) for the CandyBarZ project.
#
#	 Please note the following :
#			1. This makefile requires GNU make version 3.76.1 or later.
#			2. This makefile was written with the tab expansion set to 2.	It will probably look
#					best (comments aligned correctly, etc.) with that tab setting.
#
#===================================================================================================

OBJS			= plugin.obj
OUTPUT		=	cbzbrdr.dll

include $(CANDY)/plugins.inc
