
/******************************************************************************

  Copyright Netlabs, 1998-2000 

  http://www.netlabs.org

  (C) E. Norman, C. Wohlgemuth

******************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; see the file COPYING.  If not, write to
 * the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
 */

#define INCL_WINWORKPLACE
#include "plugin.h"
#include <stdio.h>

char tmpText[100];

//Returns the PLUGIN_INFO structure for the plugin
void CBZPluginInfo(PLUGIN_INFO * pluginInfo)
{
    strcpy(pluginInfo->PluginName, "CandyBarZ Folder backgrounds");
    strcpy(pluginInfo->PluginAuthor, "CandyBarZ Team @ OS/2 Netlabs");
    strcpy(pluginInfo->PluginDate, "Sep. 21, 2000");
    pluginInfo->lWindowTypes =  CBZ_SYSTEM ;
    return;
}

//called to allocate memory and setup initial settings
BOOL CBZInit(HINI hIni, char szName[], char szClass[], PVOID * pData)
{
    PLUGINSHARE *pPluginShare;
    PLUGINSHARE *pPluginData;
    char szReadName[128];
    char szShareName[64];
    ULONG szData;

    /* if(*pData!=NULL)*/
    //DosBeep(100,100);


    // alloc window words for the plugin's data
    if ((DosAllocMem((PPVOID) (pData),
                     sizeof(PLUGINSHARE),
                     PAG_READ | PAG_WRITE | PAG_COMMIT)) != NO_ERROR)
    {
        return FALSE;
    }

    //initialize the plugin's data to zeros.
    memset(*pData, 0, sizeof(PLUGINSHARE));

    return TRUE;
}

//change current settings.
BOOL CBZApply(char szClass[], KEY_VALUE * kv, int count, int enabledState, PVOID pData)
{
    int i;
    PLUGINSHARE *pPluginShare;
    char szShareName[32];
    char szSaveName[32];
    BOOL bDefaultApply = FALSE;
    char szName[CCHMAXPATH];
    char chrSetupString[CCHMAXPATH+100];
    HOBJECT hObject;
    
    pPluginShare = (PLUGINSHARE *) pData;

      
    //loop through each key/value pair and set appropriate parameters
    for (i = 0; i < count; i++)
      {
        if(!strcmp(kv[i].key,"DesktopBackground")) {
          strcpy(szName, kv[i].value);
          if (pPluginShare == NULL)
            {
              /* We do not reach this if in theme builder */
              sprintf(chrSetupString,"BACKGROUND=%s,N,I", szName);
              if((hObject=WinQueryObject("<WP_DESKTOP>"))!=NULLHANDLE)
                WinSetObjectData(hObject,chrSetupString); 
            }
        }
      } //end for loop
    return TRUE;
}

//save current settings to the given ini file
BOOL CBZSave(HINI hIni, char szClass[], PVOID pData, char szCustomName[])
{
    PLUGINSHARE *pPluginShare;

    char keyValue[CCHMAXPATH];
    char *ptrMem;
    ULONG ulSize;
    
    char  *key;

   
#if 0
    //write pPluginShare to the ini file!
    strcpy(szSaveName, szClass);
    strcat(szSaveName, "_SYSCOLORPlugin");
    plugin.bActiveEnabled=TRUE;
    PrfWriteProfileData(hIni,
                        "UserOptionsData",
                        szSaveName,
                        &plugin,
                        sizeof(PLUGINSHARE));
#endif
    return (TRUE);
}

//cleanup resources generated by CBZInit
BOOL CBZDestroy(HWND hwnd, PVOID pData)
{
    PLUGINSHARE *pPluginData;

    pPluginData = (PLUGINSHARE *) pData;

    if (pPluginData == NULL)
        return (TRUE);

    DosFreeMem(pPluginData);
    return (TRUE);
}

//Draw the Plugin effect into the given presentation space
BOOL CBZPluginRender(PSPAINT * pPaint, PVOID pData, short sActive)
{
    return FALSE;
}

//Called before the default wnd procedure if you wish to provide additional
//  functionality.  (i.e. modify what happens with mouse clicks, drag/drop, etc...
BOOL CBZPluginWndProc(HWND hwnd, ULONG msg, MPARAM mp1, MPARAM mp2,
                        PVOID pData, PFNWP pfnOrigWndProc, MRESULT *rc)
{

    return FALSE; //false indicates that we haven't processed the message!

}


//A Dlg procedure if the plugin has selectable settings.
MRESULT EXPENTRY CBZPluginSetupDlgProc(HWND hwnd, ULONG msg, MPARAM mp1, MPARAM mp2)
{
    short sControlId;
    PLUGINSHARE *pPluginData;
 	HOBJECT  hObject;
    char installDir[CCHMAXPATH];
    FILEDLG filedlg;
    HWND hwndDlg;

    switch (msg)
    {
    case WM_INITDLG:
      {
        if ((pPluginData = (PLUGINSHARE *) mp2) == NULL)
          {
            //Error msg..
            WinDismissDlg(hwnd, DID_ERROR);
            return (MRFROMLONG(FALSE));
          }
            WinSetWindowPtr(hwnd, QWL_USER, pPluginData);  // store window words

            WinSendMsg(WinWindowFromID(hwnd, STID_DESKTOPBACKGROUND), EM_SETTEXTLIMIT, (MPARAM) CCHMAXPATH, (MPARAM) 0);
            WinSetWindowText(WinWindowFromID(hwnd, STID_DESKTOPBACKGROUND), pPluginData->szDesktopBG);
            

      }
      break;
    case WM_COMMAND:
      {
        sControlId = COMMANDMSG(&msg)->cmd;
        
        switch (sControlId)
              {

                case PBID_OK:
                {
                    ULONG attrFound;

                    if ((pPluginData = (PLUGINSHARE *) WinQueryWindowPtr(hwnd, QWL_USER)) == NULL)
                    {
                        //Error message?
                        break;
                    }

                    WinQueryWindowText(WinWindowFromID(hwnd, STID_DESKTOPBACKGROUND), CCHMAXPATH, pPluginData->szDesktopBG);

                    //update!
                    WinDismissDlg(hwnd, PBID_OK);
                }
                break;

                case PBID_CANCEL:
                {
                    //don't update shared Memory!
                    WinDismissDlg(hwnd, PBID_CANCEL);
                }
                break;
               case PBID_BROWSEDESKTOPBG:
                {

                  //popup file change dialog!
                  memset(&filedlg, 0, sizeof(FILEDLG));  // init filedlg struct
                  
                  filedlg.cbSize = sizeof(FILEDLG);
                  filedlg.fl = FDS_OPEN_DIALOG;
                  filedlg.pszTitle = "Choose an image";
                  strcpy(filedlg.szFullFile, "*.*");
                  
                  if ((hwndDlg = WinFileDlg(HWND_DESKTOP, hwnd, &filedlg)) == NULLHANDLE)
                    {
                      return (FALSE);
                    }
                  
                  if (filedlg.lReturn != DID_OK)  // selected one
                    
                    {
                      break;
                    }
                  
                  if (sControlId == PBID_BROWSEDESKTOPBG)
                    {
                      WinSetWindowText(WinWindowFromID(hwnd, STID_DESKTOPBACKGROUND),filedlg.szFullFile);
                    }

                }
                break;
              }
            return ((MPARAM) 0);
        }

        case WM_CONTROL:
        {
            switch (SHORT1FROMMP(mp1))
            {

            }                   //end switch

            return ((MRESULT) 0);
        }                       //end WM_CONTROL

        break;

    }                           //end switch

    return (WinDefDlgProc(hwnd, msg, mp1, mp2));
}

BOOL CBZWriteAttributes(char *retStr, PVOID pData)
{
    PLUGINSHARE *pPluginData;
    char keyValue[CCHMAXPATH];
    ULONG ulSize;
    char *ptrMem;
    char  *key;
    char user[CCHMAXPATH];
    char system[CCHMAXPATH];
    int a;

    pPluginData = (PLUGINSHARE *) pData;
    /* Put this at the top */
    AddEnabledAttribute(retStr, 0);

    AddStringAttribute(retStr, "DesktopBackground", pPluginData->szDesktopBG);

    return (TRUE);

};



